Repository team-HF/HF_backend, pull requests merged in 2024-11, with the labels that each got.

#99 Chore/CICD 파이프라인 초기 구축
  Dockerfile
  Jenkinsfile
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: Chore

#91 Feature/검색 api
  src/main/java/com/hf/healthfriend/domain/follow/entity/Follow.java
  src/main/java/com/hf/healthfriend/domain/follow/repository/FollowRepository.java
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberSearchResponse.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/domain/post/controller/PostController.java
  src/main/java/com/hf/healthfriend/domain/post/dto/response/PostListObject.java
  src/main/java/com/hf/healthfriend/domain/post/service/PostService.java
  src/main/java/com/hf/healthfriend/domain/search/constant/SearchCategory.java
  src/main/java/com/hf/healthfriend/domain/search/controller/SearchController.java
  src/main/java/com/hf/healthfriend/domain/search/dto/SearchResponse.java
  src/main/java/com/hf/healthfriend/domain/search/service/SearchService.java
  src/main/java/com/hf/healthfriend/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/member/repository/MemberCustomRepositoryImlTest.java
  src/test/java/com/hf/healthfriend/domain/search/service/SearchServiceTest.java
  src/test/java/com/hf/healthfriend/testutil/RedisTestConfig.java
Labels: Feature

#93 Feature/찜하기api
  src/main/java/com/hf/healthfriend/domain/like/service/LikeService.java
  src/main/java/com/hf/healthfriend/domain/member/constant/MemberSortType.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/post/accesscontrol/PostAccessController.java
  src/main/java/com/hf/healthfriend/domain/post/exception/PostErrorCode.java
  src/main/java/com/hf/healthfriend/domain/post/exception/PostErrorResponse.java
  src/main/java/com/hf/healthfriend/domain/post/service/PostService.java
  src/main/java/com/hf/healthfriend/domain/wish/accesscontrol/WishAccessController.java
  src/main/java/com/hf/healthfriend/domain/wish/controller/WishController.java
  src/main/java/com/hf/healthfriend/domain/wish/dto/response/WishResponse.java
  src/main/java/com/hf/healthfriend/domain/wish/entity/Wish.java
  src/main/java/com/hf/healthfriend/domain/wish/repository/WishRepository.java
  src/main/java/com/hf/healthfriend/domain/wish/service/WishService.java
  src/main/java/com/hf/healthfriend/global/exception/CustomException.java
  src/main/java/com/hf/healthfriend/global/exception/ErrorCode.java
  src/main/java/com/hf/healthfriend/global/exception/ErrorControllerAdvice.java
  src/main/java/com/hf/healthfriend/global/exception/ErrorResponse.java
  src/test/java/com/hf/healthfriend/domain/wish/service/WishServiceTest.java
Labels: Feature

#95 Fix/oauth token me
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2TokenController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/DelegatingOpaqueTokenIntrospector.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/GoogleOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/KakaoOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/principal/SingleAuthorityOAuth2Principal.java
  src/main/java/com/hf/healthfriend/domain/member/accesscontrol/MemberAccessController.java
  src/main/resources/sql/init-tables.sql
Labels: bug

#97 Refactor/클라이언트에서 Presigned URL로 프로필 이미지를 직접 업로드하도록 구조 변경
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/dto/MemberDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberUpdateRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberCreationResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberUpdateResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/exceptionhandler/MemberExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/domain/spec/controller/SpecController.java
  src/main/java/com/hf/healthfriend/domain/spec/dto/SpecDto.java
  src/main/java/com/hf/healthfriend/domain/spec/service/SpecService.java
  src/main/java/com/hf/healthfriend/global/config/BeanConfig.java
  src/main/java/com/hf/healthfriend/global/file/FileUploadController.java
  src/main/java/com/hf/healthfriend/global/file/FileUploader.java
  src/main/java/com/hf/healthfriend/global/file/FileUrlResolver.java
  src/main/java/com/hf/healthfriend/global/file/image/ImageExtension.java
  src/main/java/com/hf/healthfriend/global/file/local/LocalFileUploader.java
  src/main/java/com/hf/healthfriend/global/file/local/LocalFileUrlResolver.java
  src/main/java/com/hf/healthfriend/global/jackson/deserializer/ImageExtensionDeserializer.java
  src/main/java/com/hf/healthfriend/global/jackson/deserializer/YearAndMonthDeserializer.java
  src/main/java/com/hf/healthfriend/global/jackson/serailizer/YearAndMonthSerializer.java
  src/main/java/com/hf/healthfriend/global/util/file/local/LocalFileUrlResolver.java
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/member/controller/MemberControllerMockMvcTest.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
  src/test/java/com/hf/healthfriend/domain/spec/controller/SpecControllerMockMvcTest.java
  src/test/java/com/hf/healthfriend/global/file/local/TestLocalFileUrlResolver.java
  src/test/java/com/hf/healthfriend/global/jackson/serailizer/TestYearAndMonthSerialization.java
Labels: Feature, Refactor

#103 Feature/member profile view#100
  src/main/java/com/hf/healthfriend/domain/member/dto/response/ProfileResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberJpaRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/dto/ProfileQueryResultDto.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/domain/review/dto/response/RevieweeResponseDto.java
  src/main/java/com/hf/healthfriend/domain/review/dto/response/SimpleReviewResponseDto.java
  src/main/java/com/hf/healthfriend/domain/review/repository/ReviewRepository.java
  src/main/java/com/hf/healthfriend/domain/review/repository/dto/RevieweeStatisticsQueryResultDto.java
  src/main/java/com/hf/healthfriend/domain/review/repository/querydsl/ReviewCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/review/repository/querydsl/ReviewCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/review/service/ReviewService.java
  src/main/java/com/hf/healthfriend/global/config/QueryDslConfig.java
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberJpaRepository.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
  src/test/java/com/hf/healthfriend/domain/review/repository/TestReviewRepository.java
  src/test/java/com/hf/healthfriend/domain/review/service/TestReviewService.java
  src/test/java/com/hf/healthfriend/testutil/SampleEntityGenerator.java
  src/test/java/com/hf/healthfriend/testutil/TestConfig.java
Labels: Feature, Refactor

#104 Feature/회원 프로필 보기 기능에서 프레젠테이션 레이어 구현
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/controller/schema/ProfileResponseSchema.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/test/java/com/hf/healthfriend/domain/member/controller/MemberControllerMockMvcTest.java
Labels: Feature

#106 Refactor/MemberJpaRepository와 MemberRepository 통합
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberJpaRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/domain/review/service/ReviewService.java
  src/main/java/com/hf/healthfriend/domain/wish/service/WishService.java
  src/test/java/com/hf/healthfriend/domain/comment/repository/CommentSortTest.java
  src/test/java/com/hf/healthfriend/domain/comment/repository/TestCommentRepository.java
  src/test/java/com/hf/healthfriend/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/hf/healthfriend/domain/member/repository/MemberCustomRepositoryImlTest.java
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberRepository.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
  src/test/java/com/hf/healthfriend/domain/post/PostFilteringTest.java
  src/test/java/com/hf/healthfriend/domain/review/repository/TestReviewRepository.java
  src/test/java/com/hf/healthfriend/domain/review/service/ReviewServiceSpringBootTest.java
  src/test/java/com/hf/healthfriend/domain/review/service/TestReviewService.java
  src/test/java/com/hf/healthfriend/domain/spec/service/TestSpecService.java
  src/test/java/com/hf/healthfriend/domain/wish/service/WishServiceTest.java
  src/test/java/com/hf/healthfriend/testutil/SampleEntityGenerator.java
  src/test/java/com/hf/healthfriend/testutil/TestConfig.java
Labels: Refactor

#107 Feature/소셜 로그인 시 소셜 로그인 서버에서 회원의 이름 가져오기 구현
  src/main/java/com/hf/healthfriend/auth/constant/CookieConstants.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2RedirectionController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/dto/response/GrantedTokenInfo.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateGoogleTokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateKakaoTokenSupport.java
Labels: Feature

#108 Feature/매칭 리스트 조회 비즈니스 로직 구현
  src/main/java/com/hf/healthfriend/domain/matching/constant/MatchingStatus.java
  src/main/java/com/hf/healthfriend/domain/matching/constant/MatchingStatusCondition.java
  src/main/java/com/hf/healthfriend/domain/matching/dto/response/MatchingListResponseDto.java
  src/main/java/com/hf/healthfriend/domain/matching/dto/response/PageResponseDto.java
  src/main/java/com/hf/healthfriend/domain/matching/dto/response/ProfileOfMemberInMatchingResponseDto.java
  src/main/java/com/hf/healthfriend/domain/matching/repository/MatchingRepository.java
  src/main/java/com/hf/healthfriend/domain/matching/repository/querydsl/MatchingCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/matching/repository/querydsl/MatchingCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/matching/service/MatchingService.java
  src/test/java/com/hf/healthfriend/domain/matching/repository/querydsl/TestMatchingCustomRepositoryImpl.java
Labels: Feature

#109 Feature/matching list presentation layer#105
  src/main/java/com/hf/healthfriend/domain/matching/controller/MatchingController.java
  src/main/java/com/hf/healthfriend/domain/matching/controller/schema/PaginatedMatchingListResponseSchema.java
  src/main/java/com/hf/healthfriend/domain/matching/exception/MatchingErrorCode.java
  src/main/java/com/hf/healthfriend/domain/matching/exception/MatchingExceptionHandlingControllerAdvice.java
  src/test/java/com/hf/healthfriend/domain/matching/controller/MatchingControllerMockMvcTest.java
Labels: Feature

#110 Feature/회원 등록 및 수정 시 필수값 정책 변경 반영
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/resources/sql/init-tables.sql
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberRepository.java
Labels: Feature

#112 Feature/레벨 제도 구현
  src/main/java/com/hf/healthfriend/domain/matching/entity/Matching.java
  src/main/java/com/hf/healthfriend/domain/member/domain/Tier.java
  src/main/java/com/hf/healthfriend/domain/member/dto/MemberDto.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/test/java/com/hf/healthfriend/domain/member/domain/TierTest.java
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberRepository.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
Labels: Feature

#114 Feature/매칭 제한 구현
  src/main/java/com/hf/healthfriend/domain/matching/constant/MatchingStatus.java
  src/main/java/com/hf/healthfriend/domain/matching/entity/Matching.java
  src/main/java/com/hf/healthfriend/domain/matching/exception/MatchingErrorCode.java
  src/main/java/com/hf/healthfriend/domain/matching/exception/MatchingExceptionHandlingControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/matching/exception/OutOfLimitMatchingRequestException.java
  src/main/java/com/hf/healthfriend/domain/matching/repository/querydsl/MatchingCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/matching/repository/querydsl/MatchingCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/matching/service/MatchingService.java
  src/test/java/com/hf/healthfriend/domain/matching/repository/querydsl/TestMatchingCustomRepositoryImpl.java
Labels: Feature

#115 Feature/쿠폰 발급 및 목록 조회 구현
  src/main/java/com/hf/healthfriend/domain/coupon/constant/CouponFetchType.java
  src/main/java/com/hf/healthfriend/domain/coupon/constant/CouponType.java
  src/main/java/com/hf/healthfriend/domain/coupon/dto/request/GrantCouponDto.java
  src/main/java/com/hf/healthfriend/domain/coupon/dto/request/GrantMatchingCouponDto.java
  src/main/java/com/hf/healthfriend/domain/coupon/dto/response/CouponResponseDto.java
  src/main/java/com/hf/healthfriend/domain/coupon/dto/response/MatchingCouponResponseDto.java
  src/main/java/com/hf/healthfriend/domain/coupon/entity/Coupon.java
  src/main/java/com/hf/healthfriend/domain/coupon/entity/MatchingCoupon.java
  src/main/java/com/hf/healthfriend/domain/coupon/event/handler/MatchingEventHandler.java
  src/main/java/com/hf/healthfriend/domain/coupon/event/listener/MatchingEventListenerAspect.java
  src/main/java/com/hf/healthfriend/domain/coupon/event/message/MatchingEventMessage.java
  src/main/java/com/hf/healthfriend/domain/coupon/exception/AlreadyUsedCouponException.java
  src/main/java/com/hf/healthfriend/domain/coupon/exception/AmbiguousDelegatorException.java
  src/main/java/com/hf/healthfriend/domain/coupon/exception/InvalidMatchingCountException.java
  src/main/java/com/hf/healthfriend/domain/coupon/exception/InvalidRewardException.java
  src/main/java/com/hf/healthfriend/domain/coupon/exception/NoSupportedCouponDelegatorException.java
  src/main/java/com/hf/healthfriend/domain/coupon/repository/CouponRepository.java
  src/main/java/com/hf/healthfriend/domain/coupon/repository/querydsl/CouponCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/coupon/repository/querydsl/CouponCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/coupon/service/CouponService.java
  src/main/java/com/hf/healthfriend/domain/coupon/service/CouponServiceDelegator.java
  src/main/java/com/hf/healthfriend/domain/coupon/service/CouponServiceImpl.java
  src/main/java/com/hf/healthfriend/domain/coupon/service/delegator/MatchingCouponServiceDelegator.java
  src/main/java/com/hf/healthfriend/domain/coupon/util/CouponDtoMapper.java
  src/main/java/com/hf/healthfriend/domain/coupon/util/CouponDtoMappingDelegator.java
  src/main/java/com/hf/healthfriend/domain/coupon/util/DelegatingCouponDtoMapper.java
  src/main/java/com/hf/healthfriend/domain/coupon/util/delegator/MatchingCouponDtoMappingDelegator.java
Labels: Feature

#127 Feature/닉네임 중복 체크 기능 구현
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberRepository.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/global/spec/schema/BooleanTypeSchema.java
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberRepository.java
Labels: Feature
