Repository team-HF/HF_backend, pull requests merged in 2024-10, with the labels that each got.

#58 Feature/댓글 정렬
  .gitignore
  build.gradle
  src/main/java/com/hf/healthfriend/domain/comment/constant/SortType.java
  src/main/java/com/hf/healthfriend/domain/comment/controller/CommentController.java
  src/main/java/com/hf/healthfriend/domain/comment/repository/CommentJpaRepository.java
  src/main/java/com/hf/healthfriend/domain/comment/repository/querydsl/CommentCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/comment/repository/querydsl/CommentCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/comment/service/CommentService.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/post/controller/PostController.java
  src/main/java/com/hf/healthfriend/domain/post/service/PostService.java
  src/main/java/com/hf/healthfriend/global/config/QueryDslConfig.java
  src/main/resources/application-test.yml
  src/test/java/com/hf/healthfriend/domain/comment/controller/CommentControllerMockMvcTest.java
  src/test/java/com/hf/healthfriend/domain/comment/repository/CommentSortTest.java
  src/test/java/com/hf/healthfriend/testutil/TestConfig.java
Labels: Feature

#54 Feature/경력 및 수상 이력 정보 조회 구현
  src/main/java/com/hf/healthfriend/domain/comment/controller/CommentController.java
  src/main/java/com/hf/healthfriend/domain/like/controller/LikeController.java
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/dto/MemberDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberCreationResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/exception/MemberErrorCode.java
  src/main/java/com/hf/healthfriend/domain/member/exceptionhandler/MemberExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/domain/spec/dto/SpecDto.java
  src/main/java/com/hf/healthfriend/domain/spec/entity/Spec.java
  src/main/java/com/hf/healthfriend/domain/spec/repository/SpecRepository.java
  src/main/java/com/hf/healthfriend/domain/spec/service/SpecService.java
  src/test/java/com/hf/healthfriend/domain/comment/controller/CommentControllerMockMvcTest.java
  src/test/java/com/hf/healthfriend/domain/like/controller/TestLikeControllerMockMvc.java
  src/test/java/com/hf/healthfriend/domain/member/controller/TestMemberController.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
  src/test/java/com/hf/healthfriend/domain/spec/service/TestSpecService.java
Labels: Feature

#67 Feat/ 목록 카테고리 필터링
  src/main/java/com/hf/healthfriend/domain/post/controller/PostController.java
  src/main/java/com/hf/healthfriend/domain/post/dto/response/PostListObject.java
  src/main/java/com/hf/healthfriend/domain/post/repository/PostRepository.java
  src/main/java/com/hf/healthfriend/domain/post/repository/querydsl/PostCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/post/repository/querydsl/PostCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/post/service/PostService.java
  src/test/java/com/hf/healthfriend/domain/post/PostFilteringTest.java
Labels: Refactor

#66 Feature/마이페이지 기획 변경 및 추가사항 반영
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberUpdateRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberUpdateResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/member/exception/FitnessLevelUpdateException.java
  src/main/java/com/hf/healthfriend/domain/member/exception/MemberErrorCode.java
  src/main/java/com/hf/healthfriend/domain/member/exceptionhandler/MemberExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/member/repository/dto/MemberUpdateDto.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/global/util/mapping/BeanMapper.java
  src/main/java/com/hf/healthfriend/global/util/mapping/BeanMapping.java
  src/main/java/com/hf/healthfriend/global/util/mapping/MappingAttribute.java
  src/main/java/com/hf/healthfriend/global/util/mapping/exception/InvalidTargetNameException.java
  src/test/java/com/hf/healthfriend/domain/like/controller/TestLikeControllerMockMvc.java
  src/test/java/com/hf/healthfriend/domain/member/controller/TestMemberController.java
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberJpaRepository.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
  src/test/java/com/hf/healthfriend/global/util/mapping/SampleSourceClass.java
  src/test/java/com/hf/healthfriend/global/util/mapping/SampleTargetClass.java
  src/test/java/com/hf/healthfriend/global/util/mapping/TestBeanMapper.java
  src/test/java/com/hf/healthfriend/testutil/SampleEntityGenerator.java
Labels: Feature, Refactor

#71 Feature/연관관계가 있는 테이블의 레코드가 있는지 확인
  src/main/java/com/hf/healthfriend/domain/comment/controller/exceptionhandler/CommentErrorCode.java
  src/main/java/com/hf/healthfriend/domain/comment/controller/exceptionhandler/CommentExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/comment/exception/PostNotFoundException.java
  src/main/java/com/hf/healthfriend/domain/comment/service/CommentService.java
  src/main/java/com/hf/healthfriend/domain/spec/exception/SpecErrorCode.java
  src/main/java/com/hf/healthfriend/domain/spec/exception/SpecExceptionHandlingControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/spec/service/SpecService.java
  src/test/java/com/hf/healthfriend/domain/comment/service/TestCommentService.java
  src/test/java/com/hf/healthfriend/domain/spec/service/TestSpecService.java
Labels: Feature

#73 Feature/리뷰 생성
  src/main/java/com/hf/healthfriend/domain/matching/entity/Matching.java
  src/main/java/com/hf/healthfriend/domain/matching/exception/MatchingNotFoundException.java
  src/main/java/com/hf/healthfriend/domain/matching/repository/MatchingRepository.java
  src/main/java/com/hf/healthfriend/domain/review/accesscontrol/ReviewAccessController.java
  src/main/java/com/hf/healthfriend/domain/review/constants/EvaluationType.java
  src/main/java/com/hf/healthfriend/domain/review/controller/ReviewController.java
  src/main/java/com/hf/healthfriend/domain/review/dto/request/ReviewCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/review/entity/Review.java
  src/main/java/com/hf/healthfriend/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/hf/healthfriend/domain/review/exception/ReviewExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/review/repository/ReviewRepository.java
  src/main/java/com/hf/healthfriend/domain/review/service/ReviewService.java
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/review/service/TestReviewService.java
Labels: Feature

#72 Feature/인기글 목록 조회
  build.gradle
  src/main/java/com/hf/healthfriend/domain/like/repository/LikeRepository.java
  src/main/java/com/hf/healthfriend/domain/like/service/LikeService.java
  src/main/java/com/hf/healthfriend/domain/post/controller/PostController.java
  src/main/java/com/hf/healthfriend/domain/post/dto/response/PostGetResponse.java
  src/main/java/com/hf/healthfriend/domain/post/entity/Post.java
  src/main/java/com/hf/healthfriend/domain/post/repository/PostRepository.java
  src/main/java/com/hf/healthfriend/domain/post/repository/querydsl/PostCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/post/repository/querydsl/PostCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/post/service/PostService.java
  src/main/java/com/hf/healthfriend/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/post/PostFilteringTest.java
  src/test/java/com/hf/healthfriend/domain/post/service/PopularPostListTest.java
  src/test/java/com/hf/healthfriend/testutil/RedisTestConfig.java
Labels: Feature

#75 Feature/특정 회원에 대한 리뷰 조회
  src/main/java/com/hf/healthfriend/domain/matching/entity/Matching.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/review/controller/ReviewController.java
  src/main/java/com/hf/healthfriend/domain/review/controller/schema/RevieweeResponseSchema.java
  src/main/java/com/hf/healthfriend/domain/review/dto/ReviewDetailDto.java
  src/main/java/com/hf/healthfriend/domain/review/dto/request/ReviewCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/review/dto/response/ReviewDetailPerEvaluationType.java
  src/main/java/com/hf/healthfriend/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/hf/healthfriend/domain/review/dto/response/RevieweeResponseDto.java
  src/main/java/com/hf/healthfriend/domain/review/entity/Review.java
  src/main/java/com/hf/healthfriend/domain/review/repository/ReviewRepository.java
  src/main/java/com/hf/healthfriend/domain/review/repository/dto/RevieweeStatisticsMapping.java
  src/main/java/com/hf/healthfriend/domain/review/repository/querydsl/ReviewCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/review/repository/querydsl/ReviewCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/review/service/ReviewService.java
  src/test/java/com/hf/healthfriend/domain/review/repository/TestReviewRepository.java
  src/test/java/com/hf/healthfriend/domain/review/service/TestReviewService.java
  src/test/java/com/hf/healthfriend/testutil/SampleEntityGenerator.java
Labels: Feature

#84 Documentation/경력 및 수상 이력 API 문서 및 테스트 코드 작성
  src/main/java/com/hf/healthfriend/domain/review/exception/ReviewExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/spec/controller/SpecController.java
  src/main/java/com/hf/healthfriend/domain/spec/controller/schema/ListSpecDtoSchema.java
  src/main/java/com/hf/healthfriend/domain/spec/controller/schema/SpecUpdateRequestDtoListSchema.java
  src/main/java/com/hf/healthfriend/domain/spec/controller/schema/SpecUpdateResponseDtoSchema.java
  src/main/java/com/hf/healthfriend/domain/spec/exception/SpecErrorCode.java
  src/main/java/com/hf/healthfriend/domain/spec/exception/SpecExceptionHandlingControllerAdvice.java
  src/main/java/com/hf/healthfriend/global/spec/schema/LongTypeListSchema.java
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/spec/controller/SpecControllerMockMvcTest.java
Labels: Documentation, Test

#86 Refactor/회원 API 테스트 리팩토링
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberCreationResponseDto.java
  src/test/java/com/hf/healthfriend/domain/member/controller/MemberControllerMockMvcTest.java
Labels: Test, Refactor

#88 chore: 데이터베이스 init script 레포지토리에 포함
  src/main/resources/sql/init-tables.sql
Labels: Chore

#90 Feature/매칭 기능 추가 구현
  src/main/java/com/hf/healthfriend/domain/matching/dto/MatchingResponseDto.java
  src/main/java/com/hf/healthfriend/domain/matching/dto/request/MatchingRequestDto.java
  src/main/java/com/hf/healthfriend/domain/matching/entity/Matching.java
  src/main/java/com/hf/healthfriend/domain/matching/service/MatchingService.java
  src/main/java/com/hf/healthfriend/domain/review/entity/Review.java
  src/main/java/com/hf/healthfriend/domain/review/exception/DuplicateReviewException.java
  src/main/java/com/hf/healthfriend/domain/review/exception/ReviewBeforeMeetingException.java
  src/main/java/com/hf/healthfriend/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/hf/healthfriend/domain/review/exception/ReviewExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/review/repository/ReviewRepository.java
  src/main/java/com/hf/healthfriend/domain/review/repository/querydsl/ReviewCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/review/repository/querydsl/ReviewCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/review/service/ReviewService.java
  src/test/java/com/hf/healthfriend/domain/comment/controller/CommentControllerMockMvcTest.java
  src/test/java/com/hf/healthfriend/domain/matching/service/TestMatchingService.java
  src/test/java/com/hf/healthfriend/domain/review/repository/TestReviewRepository.java
  src/test/java/com/hf/healthfriend/domain/review/service/ReviewServiceSpringBootTest.java
  src/test/java/com/hf/healthfriend/domain/review/service/TestReviewService.java
Labels: Feature
