Repository team-HF/HF_backend, pull requests merged in 2024-12, with the labels that each got.

#131 Fix/카테고리값변경
  src/main/java/com/hf/healthfriend/domain/comment/dto/CommentDto.java
  src/main/java/com/hf/healthfriend/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/hf/healthfriend/domain/comment/exception/CommentErrorControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/comment/exception/errorcode/CommentErrorCode.java
  src/main/java/com/hf/healthfriend/domain/comment/exception/handler/CommentExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/comment/service/CommentService.java
  src/main/java/com/hf/healthfriend/domain/post/dto/response/PostGetResponse.java
Labels: Refactor

#129 Fix/MemberCustomRepository.findByMemberId에 예외 발생하던 거 고침
  src/main/java/com/hf/healthfriend/domain/member/repository/querydsl/MemberCustomRepositoryImpl.java
  src/test/java/com/hf/healthfriend/domain/member/repository/MemberCustomRepositoryImlTest.java
Labels: bug

#134 Feature: GET /posts/{postId}/likes 엔드포인트 명세 변경
  src/main/java/com/hf/healthfriend/domain/like/controller/LikeController.java
  src/main/java/com/hf/healthfriend/domain/like/repository/LikeRepository.java
  src/main/java/com/hf/healthfriend/domain/like/service/LikeService.java
  src/test/java/com/hf/healthfriend/domain/like/repository/LikeRepositoryTest.java
Labels: Feature, Refactor

#146 Feature/ 알림 기능
  build.gradle
  src/main/java/com/hf/healthfriend/domain/comment/repository/CommentJpaRepository.java
  src/main/java/com/hf/healthfriend/domain/comment/service/CommentService.java
  src/main/java/com/hf/healthfriend/domain/like/service/LikeService.java
  src/main/java/com/hf/healthfriend/domain/matching/service/MatchingService.java
  src/main/java/com/hf/healthfriend/domain/notification/constant/NotificationGetType.java
  src/main/java/com/hf/healthfriend/domain/notification/constant/NotificationType.java
  src/main/java/com/hf/healthfriend/domain/notification/consumer/DBWorker.java
  src/main/java/com/hf/healthfriend/domain/notification/consumer/SseWorker.java
  src/main/java/com/hf/healthfriend/domain/notification/controller/NotificationController.java
  src/main/java/com/hf/healthfriend/domain/notification/controller/SseController.java
  src/main/java/com/hf/healthfriend/domain/notification/dto/Alarm.java
  src/main/java/com/hf/healthfriend/domain/notification/dto/NotificationEvent.java
  src/main/java/com/hf/healthfriend/domain/notification/dto/NotificationResponse.java
  src/main/java/com/hf/healthfriend/domain/notification/entity/Notification.java
  src/main/java/com/hf/healthfriend/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/hf/healthfriend/domain/notification/exception/NotificationErrorControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/notification/exception/NotificationErrorResponse.java
  src/main/java/com/hf/healthfriend/domain/notification/exception/NotificationException.java
  src/main/java/com/hf/healthfriend/domain/notification/publisher/NotificationPublisher.java
  src/main/java/com/hf/healthfriend/domain/notification/repository/EmitterRepository.java
  src/main/java/com/hf/healthfriend/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/com/hf/healthfriend/domain/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/hf/healthfriend/domain/notification/service/NotificationPublishService.java
  src/main/java/com/hf/healthfriend/domain/notification/service/NotificationSSEService.java
  src/main/java/com/hf/healthfriend/domain/notification/service/NotificationService.java
  src/main/java/com/hf/healthfriend/domain/notification/util/JsonUtils.java
  src/main/java/com/hf/healthfriend/domain/notification/util/NotificationMessageGenerator.java
  src/main/java/com/hf/healthfriend/domain/review/service/ReviewService.java
  src/main/java/com/hf/healthfriend/global/config/AWSConfig.java
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/notification/consumer/DBWorkerTest.java
  src/test/java/com/hf/healthfriend/domain/notification/consumer/SseWorkerTest.java
Labels: Feature
