Repository team-HF/HF_backend, pull requests merged in 2024-09, with the labels that each got.

#8 Feat: 토큰 재발급 구현
  build.gradle
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/constant/SecurityConstants.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2RedirectionController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2TokenController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/dto/response/TokenRefreshResponseDto.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/GoogleOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/KakaoOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/GoogleOAuth2TokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/KakaoOAuth2TokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/OAuth2TokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateGoogleTokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateKakaoTokenSupport.java
  src/main/resources/application.yml
Labels: Feature

#11 Chore: 프론트에서 통합 테스트를 위한 내장 데이터베이스 설정
  build.gradle
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberRepository.java
Labels: Chore

#12 Refactor: 소셜 로그인 로직 변경
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2RedirectionController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2TokenController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/dto/request/WrappingRefreshTokenWithCookieRequestDto.java
  src/main/java/com/hf/healthfriend/auth/oauth2/dto/response/TokenValidationInfo.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/DelegatingOpaqueTokenIntrospector.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/GoogleOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/KakaoOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/principal/SingleAuthorityOAuth2Principal.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/OAuth2TokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateGoogleTokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateKakaoTokenSupport.java
  src/main/java/com/hf/healthfriend/domain/member/constant/Role.java
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/dto/MemberDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberCreationResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/member/exception/NoSuchMemberException.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/global/config/BeanConfig.java
  src/main/java/com/hf/healthfriend/global/spec/ApiBasicResponse.java
  src/main/java/com/hf/healthfriend/global/util/NoSecurityHttpCookieUtils.java
  src/main/resources/application-constants.yml
  src/main/resources/application.yml
Labels: Refactor

#14 Docs: 기본 Swagger 설정
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/exception/CustomBearerTokenAuthenticationException.java
  src/main/java/com/hf/healthfriend/auth/exception/base/CustomAuthenticationException.java
  src/main/java/com/hf/healthfriend/auth/exceptionhandling/AuthenticationExceptionHandler.java
  src/main/java/com/hf/healthfriend/auth/exceptionhandling/OAuth2AuthenticationExceptionHandler.java
  src/main/java/com/hf/healthfriend/auth/filter/AuthExceptionHandlerFilter.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2TokenController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/DelegatingOpaqueTokenIntrospector.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/GoogleOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/KakaoOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/domain/Sample.java
  src/main/java/com/hf/healthfriend/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/hf/healthfriend/domain/member/exceptionhandler/MemberExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/global/config/SwaggerConfig.java
  src/main/java/com/hf/healthfriend/global/exception/ErrorCode.java
  src/main/java/com/hf/healthfriend/global/exception/ExControllerAdvice.java
  src/main/java/com/hf/healthfriend/global/exception/GlobalExceptionHandelrControllerAdvice.java
  src/main/java/com/hf/healthfriend/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/hf/healthfriend/global/exception/errorcode/ErrorCode.java
  src/main/java/com/hf/healthfriend/global/spec/ApiBasicResponse.java
  src/main/java/com/hf/healthfriend/global/spec/ApiErrorResponse.java
Labels: Documentation

#18 Test: Member 서브시스템 테스트 코드 추가
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/filter/AccessControlFilter.java
  src/main/java/com/hf/healthfriend/auth/filter/AccessDeniedExceptionResolverFilter.java
  src/main/java/com/hf/healthfriend/auth/filter/AuthExceptionHandlerFilter.java
  src/main/java/com/hf/healthfriend/domain/Sample.java
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/dto/MemberUpdateDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/hf/healthfriend/global/config/BeanConfig.java
  src/main/java/com/hf/healthfriend/global/util/SecuredHttpCookieUtils.java
  src/test/java/com/hf/healthfriend/domain/member/controller/TestMemberController.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
Labels: Documentation, Test

#22 Refactor: 백엔드에서 OAuth 2.0 소셜 로그인 처리
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/constant/CookieConstants.java
  src/main/java/com/hf/healthfriend/auth/constant/SecurityConstants.java
  src/main/java/com/hf/healthfriend/auth/exception/InvalidCodeException.java
  src/main/java/com/hf/healthfriend/auth/exception/InvalidRefreshTokenException.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2RedirectionController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2TokenController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/exceptionhandler/OAuth2ExceptionHandler.java
  src/main/java/com/hf/healthfriend/auth/oauth2/dto/response/OAuth2LoginResponseDto.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/OAuth2TokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateGoogleTokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateKakaoTokenSupport.java
  src/main/java/com/hf/healthfriend/domain/member/dto/request/MemberCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberCreationResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/global/exception/ErrorCode.java
  src/main/java/com/hf/healthfriend/global/spec/schema/MemberCreationResponseSchema.java
  src/main/java/com/hf/healthfriend/global/spec/schema/OAuth2LoginResponseSchema.java
  src/main/java/com/hf/healthfriend/global/spec/schema/TokenRefreshResponseSchema.java
  src/main/java/com/hf/healthfriend/global/util/SecuredHttpCookieUtils.java
  src/main/resources/application-constants.yml
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
Labels: Documentation, Refactor

#25 Feat: 소셜 로그인 후 리다이렉션하는 로직 추가
  .gitignore
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/constant/CookieConstants.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2RedirectionController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2TokenController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/exceptionhandler/OAuth2ExceptionHandler.java
  src/main/java/com/hf/healthfriend/global/util/HttpCookieUtils.java
  src/main/java/com/hf/healthfriend/global/util/SecuredHttpCookieUtils.java
  src/main/resources/application-constants.yml
  src/main/resources/application.yml
Labels: Feature

#29 Feat: 소셜 로그인 성공 시 프론트엔드의 마이페이지로 리다이렉션
  src/main/java/com/hf/healthfriend/auth/accesscontrol/AccessControlTrigger.java
  src/main/java/com/hf/healthfriend/auth/accesscontrol/AccessController.java
  src/main/java/com/hf/healthfriend/auth/filter/AccessDeniedExceptionResolverFilter.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2RedirectionController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/exceptionhandler/OAuth2ExceptionHandler.java
  src/main/java/com/hf/healthfriend/domain/member/accesscontrol/MemberAccessController.java
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/global/config/ServletConfig.java
  src/main/resources/application.yml
Labels: Feature

#37 feat: 인증/인가 로직 끄는 설정
  src/main/java/com/hf/healthfriend/auth/authentication/NoAuthAuthentication.java
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/filter/JsonParserFilter.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/DelegatingOpaqueTokenIntrospector.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/GoogleOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/KakaoOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/JsonBasedTokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateGoogleTokenSupport.java
  src/main/java/com/hf/healthfriend/auth/oauth2/tokensupport/RestTemplateKakaoTokenSupport.java
Labels: Feature

#41 Feature/댓글 crud#35
  src/main/java/com/hf/healthfriend/auth/config/SecurityConfig.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2RedirectionController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/controller/OAuth2TokenController.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/DelegatingOpaqueTokenIntrospector.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/GoogleOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/auth/oauth2/introspect/delegator/KakaoOpaqueTokenIntrospectorDelegator.java
  src/main/java/com/hf/healthfriend/domain/BaseTimeEntity.java
  src/main/java/com/hf/healthfriend/domain/comment/accesscontrol/CommentAccessController.java
  src/main/java/com/hf/healthfriend/domain/comment/controller/CommentController.java
  src/main/java/com/hf/healthfriend/domain/comment/controller/exceptionhandler/CommentErrorCode.java
  src/main/java/com/hf/healthfriend/domain/comment/controller/exceptionhandler/CommentExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/comment/dto/CommentDto.java
  src/main/java/com/hf/healthfriend/domain/comment/dto/request/CommentCreationRequestDto.java
  src/main/java/com/hf/healthfriend/domain/comment/dto/response/CommentCreationResponseDto.java
  src/main/java/com/hf/healthfriend/domain/comment/entity/Comment.java
  src/main/java/com/hf/healthfriend/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/hf/healthfriend/domain/comment/repository/CommentJpaRepository.java
  src/main/java/com/hf/healthfriend/domain/comment/repository/CommentRepository.java
  src/main/java/com/hf/healthfriend/domain/comment/repository/dto/CommentUpdateDto.java
  src/main/java/com/hf/healthfriend/domain/comment/service/CommentService.java
  src/main/java/com/hf/healthfriend/domain/member/accesscontrol/MemberAccessController.java
  src/main/java/com/hf/healthfriend/domain/member/controller/MemberController.java
  src/main/java/com/hf/healthfriend/domain/member/dto/MemberDto.java
  src/main/java/com/hf/healthfriend/domain/member/dto/response/MemberCreationResponseDto.java
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberJpaRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberRepository.java
  src/main/java/com/hf/healthfriend/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/hf/healthfriend/domain/member/service/MemberService.java
  src/main/java/com/hf/healthfriend/domain/post/dto/request/PostWriteRequest.java
  src/main/java/com/hf/healthfriend/domain/post/entity/Post.java
  src/main/java/com/hf/healthfriend/domain/post/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/hf/healthfriend/domain/comment/controller/CommentControllerMockMvcTest.java
  src/test/java/com/hf/healthfriend/domain/comment/repository/TestCommentRepository.java
  src/test/java/com/hf/healthfriend/domain/comment/service/TestCommentService.java
  src/test/java/com/hf/healthfriend/domain/member/controller/TestMemberController.java
  src/test/java/com/hf/healthfriend/domain/member/repository/TestMemberJpaRepository.java
  src/test/java/com/hf/healthfriend/domain/member/service/TestMemberService.java
Labels: Feature, Refactor

#48 Feature/좋아요 기능 구현
  src/main/java/com/hf/healthfriend/domain/like/controller/LikeController.java
  src/main/java/com/hf/healthfriend/domain/like/controller/schema/LikeDtoListSchema.java
  src/main/java/com/hf/healthfriend/domain/like/controller/schema/LikeDtoSchema.java
  src/main/java/com/hf/healthfriend/domain/like/dto/LikeDto.java
  src/main/java/com/hf/healthfriend/domain/like/entity/Like.java
  src/main/java/com/hf/healthfriend/domain/like/exception/DuplicateLikeException.java
  src/main/java/com/hf/healthfriend/domain/like/exception/LikeErrorCode.java
  src/main/java/com/hf/healthfriend/domain/like/exception/LikeErrorControllerAdvice.java
  src/main/java/com/hf/healthfriend/domain/like/exception/PostOrMemberNotExistsException.java
  src/main/java/com/hf/healthfriend/domain/like/repository/LikeRepository.java
  src/main/java/com/hf/healthfriend/domain/like/service/LikeService.java
  src/main/java/com/hf/healthfriend/domain/member/exceptionhandler/MemberExceptionHandlerControllerAdvice.java
  src/main/java/com/hf/healthfriend/global/spec/BasicErrorResponse.java
  src/main/java/com/hf/healthfriend/global/spec/schema/LongTypeSchema.java
  src/test/java/com/hf/healthfriend/domain/like/controller/TestLikeControllerMockMvc.java
  src/test/java/com/hf/healthfriend/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/hf/healthfriend/domain/like/service/LikeServiceTest.java
Labels: Feature

#53 Feature/경력 및 수상이력 추가 기능 구현
  src/main/java/com/hf/healthfriend/domain/member/entity/Member.java
  src/main/java/com/hf/healthfriend/domain/spec/dto/SpecDto.java
  src/main/java/com/hf/healthfriend/domain/spec/entity/Spec.java
  src/main/java/com/hf/healthfriend/domain/spec/repository/SpecRepository.java
  src/main/java/com/hf/healthfriend/domain/spec/service/SpecService.java
  src/test/java/com/hf/healthfriend/domain/spec/service/TestSpecService.java
  src/test/java/com/hf/healthfriend/testutil/SampleEntityGenerator.java
Labels: Feature

#52 Feature/검색
  src/main/java/com/hf/healthfriend/domain/comment/repository/CommentJpaRepository.java
  src/main/java/com/hf/healthfriend/domain/post/controller/PostController.java
  src/main/java/com/hf/healthfriend/domain/post/dto/request/PostWriteRequest.java
  src/main/java/com/hf/healthfriend/domain/post/dto/response/PostGetResponse.java
  src/main/java/com/hf/healthfriend/domain/post/dto/response/PostListObject.java
  src/main/java/com/hf/healthfriend/domain/post/entity/Post.java
  src/main/java/com/hf/healthfriend/domain/post/repository/PostRepository.java
  src/main/java/com/hf/healthfriend/domain/post/service/PostService.java
  src/test/java/com/hf/healthfriend/domain/post/service/PostServiceTest.java
Labels: Feature
